import Head from "next/head";
import Home from "../components/Home/Home";
import Dashboard from "../components/Dashboard/Main/Dashboard";
import { auth } from "../firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import { StyleSheetManager } from "styled-components";

export default function Index() {
  const [user, loading] = useAuthState(auth);

  return (
    <div>
      <Head>
        <title>Crypto Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyleSheetManager disableCSSOMInjection>
        {!user ? <Home /> : <Dashboard />}
      </StyleSheetManager>
    </div>
  );
}
